name: CI

on:
  workflow_dispatch:
  push:
  pull_request:


defaults:
  run:
    shell: bash -l {0}


jobs:

  test-browser:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.2"]

    steps:
      - uses: actions/checkout@v2

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: build-env.yaml
          environment-name: build-env
          micromamba-version: "0.22.0"

      - name:
        run: |
          micromamba activate build-env
          npm install
          npm run build:with_micromamba

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false